---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: harpoon
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: harpoon
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: harpoon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: harpoon
subjects:
  - kind: ServiceAccount
    name: harpoon
    namespace: default
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: harpoon
  namespace: default
  labels:
    k8s-app: harpoon
spec:
  selector:
    matchLabels:
      name: harpoon
  template:
    metadata:
      labels:
        name: harpoon
    spec:
      serviceAccountName: harpoon
      initContainers:
        - name: harpoon
          image: ghcr.io/adrianchifor/harpoon:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: docker
              mountPath: /var/run/docker.sock
              # mountPath: /run/crio/crio.sock (for cri-o)
      volumes:
        - name: docker
          hostPath:
            path: /var/run/docker.sock
      containers:
        - name: pause
          image: gcr.io/google_containers/pause
